### ISSUE TITLE
Websocket not connecting

### ISSUE THREAD

**Issue by JimInCO** [BrendanAndrade/web-matlab-bridge#5]
When I attempt to run the first two lines of **example.m**

```
master_uri = 'ws://localhost:9090';
ws = ros_websocket(master_uri);
```

A java applet appears saying the Java Websocket is open and allowing me to manually close the Websocket, but when it tries to connect the following error occurs

``` matlab
Error using ros_websocket (line 87)
Java exception occurred:
java.lang.IllegalStateException: WebSocketClient objects are not reuseable

    at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:153)


java.net.ConnectException: Connection refused: connect
    at sun.nio.ch.Net.connect(Native Method)
    at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
    at org.java_websocket.client.WebSocketClient.tryToConnect(WebSocketClient.java:201)
    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:219)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:209)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-59" java.lang.NullPointerException
    at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:446)
    at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:475)
    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:232)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:209)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by JimInCO** [comment]
I setup my javaclasspath by changing my classpath.txt file to add the Java-Websocket jar file,
web-matlab-bridge\Java-WebSocket\dist\java_websocket.jar

Might I have missed something in how to correctly setup the package?

**Comment by JimInCO** [comment]
It looks like it was on my end. I didn't have a websocket server properly setup. Maybe the README.md file could include some information on how to setup properly do the setup.
